### ISSUE TITLE
Templates as class attributes issue

### ISSUE THREAD

**Issue by autoditactics** [migaku-official/Migaku-Editor-Addon#1]
**Type:**
  - [x] bug  
  - [ ] feature
  - [ ] enhancement
  - [ ] question
 
**Environment:**
  - OS: MacOS (but I imagine others as well)
 
**Going to open a PR:**
  - [ ] yes
  - [x] no
 
**Description:**  
Using templates as class attributes results in unexpected behaviour. For example, if we had a monolingual card indicator that was only visible when the card had the tag "jp-jp" then the relevant HTML might look like `<span style="opacity: 0" class="{{Tags}}">JP-JP</span>` with the CSS `span[class*="jp-jp"] {opacity: 0.6 !important;}`. With this bug, this code no longer functions, and an additional `">` appears on the card.

**Comment by TowelSniffer** [comment]
I ran into the same error for some of my cards but there is a workaround. put the class attribute inside a hidden div and reference it with js

for instance, I have an iframe with a field containing the like like so 

```
<span id='link' style ="display:none">{{Link}}</span>

<span id='iframe'></span>

<script>
var iframe = document.getElementById("iframe");
var link = document.getElementById("link").innerHTML.replace(/<[^>]*>?/gm, '');

iframe.innerHTML="<iframe width='85%' height='594' src='"+link+"' frameborder='0' allowfullscreen allow='autoplay; fullscreen'></iframe>"
</script>{{/Link}}

```


the .replace(/<[^>]*>?/gm, '') gets rid of the hidden addition made by this addon

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
