### ISSUE TITLE
Replacement issue with nested div tags in card templates

### ISSUE THREAD

**Issue by gorgonical** [migaku-official/Migaku-Editor-Addon#5]
I am not sure if I brought this issue on because I tinkered with my card template, or what. However, I found that the text replacement fails if card fields are nested. That is, if div tags are nested, the regular expression fails to match them correctly.

This problem is not surprising, however, because regular expressions aren't actually capable of paren-balancing (extended regexes can, but it's messy). You need at least a stack-based solution, I think.

Since you have balanced tags it's really similar to a calculator. An outline of how to build the modified text would be:
1. Check each character in the template (or word, whatever) and insert it unless it meets point 2 below.
2. Finding an opening div tag means push the changed version (the one with the new JS) onto the stack plus a unique token, and insert the changed, unfinished version with this token instead of the field name we need.
3. When you find a matching fieldname, find the div tag on the top of the stack, get its token, and find that token in the text you've already accumulated and replace it with the fieldname. Push the fieldname onto the stack. Insert the fieldname.
4. When a closing div tag is found, pop the top two elements off the stack and insert them into the text along with the closing div tag.
5. All other text is just inserted into the replacement text as normal.

If I understand the goal correctly, this solves the problem and shouldn't be too slow. Considering that the size of the template text is only maybe a thousand characters, searching character-wise shouldn't be an issue. It can maybe be improved by splitting the text on "<div", but I bet Python does a character-wise search anyway.

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.
