### ISSUE TITLE
Conflict with "Extended Tag Add/Edit Dialog" Addon

### ISSUE THREAD

**Issue by Rudo2204** [migaku-official/Migaku-Editor-Addon#6]
Migaku Editor addon conflicts with the [Extended Tag Add/Edit Dialog addon](https://ankiweb.net/shared/info/1135507717).
If both is install and you try to edit a card with Migaku Editor addon it will throw this error:
`TypeError: 'QWidget' object is not callable`

**Comment by KieranBrannigan** [comment]
Unfortunately we can't guarantee that our addons will be compatible with other 3rd party addons.
